### PR TITLE
Added SNOWCLI_EXTRA_LIBS option for shared libs

### PR DESCRIPTION
**Pull request by sfc-gh-cconner**

### CODE REVIEW

**Comment by sfc-gh-jhollan** [comment]
Thank you for creating this! In general I like it - a few thoughts (and happy to try to add to take to finish line):

1. I wonder if we can have this work with directories as well as individual files. `PYTHONPATH` today I think does so by directories so could be consistent.
2. Naming. I wonder if we call this like `SNOWCLI_INCLUDE_LIBS` or `SNOWCLI_INCLUDE_PATHS` or something?

**Comment by sfc-gh-cconner** [comment]
Sounds good, I'll play around with it some.

**Comment by sfc-gh-cconner** [comment]
Made the recommended changes!

**Review by sfc-gh-jhollan — APPROVED** [review]
This is awesome! Thank you

**Pull request merged**
