### PR TITLE
Fix build failures

### PR DESCRIPTION
**Pull request by sfc-gh-zblackwood**

### CODE REVIEW

**Comment by sfc-gh-zblackwood** [comment]
Grrr...can't get this to work -- trying to replace the `/` from github.ref_name so that the builds don't always fail, but haven't figured it out yet

**Comment by sfc-gh-turbaszek** [comment]
@sfc-gh-zblackwood we used sha instead of ref_name in artefact name. The builds are working, should we close this PR?

**Comment by sfc-gh-turbaszek** [comment]
@sfc-gh-zblackwood we used sha instead of ref_name in artefact name. The builds are working, so I'm closing this PR.

**Comment by sfc-gh-zblackwood** [comment]
Thanks @sfc-gh-turbaszek!

**Pull request closed without merging**
